---
# =============================================
# .yamllint.yml 文件
# 作用：配置 yamllint 工具的全局校验规则
# 该配置文件作为整个仓库的基准（base），所有 YAML 文件都会继承这些规则
# =============================================

# 忽略校验的文件或目录（完全跳过 lint 检查）
ignore: |
  *.encrypted.yaml               # 跳过所有被 sops 加密的 YAML 文件（含密钥，不应格式化）
  *.enc.yaml                     # 同上，另一种加密文件后缀
  **/kubernetes/clusters/**      # 跳过所有集群特定目录（每个集群差异大，避免误报）
  talos/                         # Talos 机器配置由 talhelper 生成，格式固定，不参与 lint
  .github/workflows/             # GitHub Actions 工作流（CI）语法特殊，yamllint 经常误报
  .taskfiles/                    # Taskfile 子目录，包含大量动态生成内容

# 继承 yamllint 官方默认配置（default），然后在此基础上覆盖/增强规则
extends: default

# 自定义规则
rules:
  # 禁止重复的字典键（duplicate key），非常重要，能避免严重配置错误
  key-duplicates: enable

  # 缩进规则：全仓库统一使用 2 个空格缩进
  indentation:
    spaces: 2                    # 必须使用 2 个空格（不允许 tab 或 4 空格）
    indent-sequences: consistent # 列表（-）缩进风格保持一致即可（可与父节点对齐或悬挂）
    check-multi-line-strings: false  # 不检查多行字符串（|> |）内的缩进

  # 单行最大长度设为 240（远高于默认 80），适合宽屏和复杂 K8s 资源
  line-length:
    max: 240
    level: warning               # 超长只警告，不阻塞 CI
    allow-non-breakable-words: true         # URL、UUID 等不允许折行
    allow-non-breakable-inline-mappings: true  # 行内 { } 映射过长也不强制折行

  # 禁止行尾空格（trailing spaces）
  trailing-spaces: enable

  # 文件结尾必须有且仅有一个换行符（POSIX 标准）
  new-line-at-end-of-file: enable

  # truthy 类型值只允许以下写法（防止 true/True/TRUE 混用导致歧义）
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
    check-keys: false            # 不检查 key 为 true/false 的情况

  # 注释格式要求
  comments:
    require-starting-space: true   # # 后面必须有一个空格，例如 #正确  而不是 #错误
    min-spaces-from-content: 1     # 代码与行内注释之间至少隔 1 个空格（推荐 2 个）

  # 大括号 { } 内部空格严格要求（K8s inline 表达式常见）
  braces:
    min-spaces-inside: 0           # {前 {后可以无空格 → {var}
    max-spaces-inside: 1           # 最多允许 1 个空格 → { var }
    min-spaces-inside-empty: 0     # 空大括号 {} 内部无空格
    max-spaces-inside-empty: 0

  # 中括号 [ ] 同上要求
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  # 文档开始标记 --- 必须存在（方便多文档 YAML）
  document-start:
    present: true                  # 强制要求每个 YAML 文件以 --- 开头

  # 文档结束标记 ... 不要求（大多数情况不需要）
  document-end:
    present: false